language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mattstone93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mattstone93/docker-react npm run test
